import { createSlice, createAsyncThunk } from '@reduxjs/toolkit';
import { URLS } from '../../constants/urls';
import axios, { AxiosError } from 'axios';

// Thunk for searching resources based on a search term
export const getProjects = createAsyncThunk('projects/getProjects', async (requestData: any , { rejectWithValue }) => {
  try {
    // search from your API endpoint 
    axios.defaults.headers.common['Authorization'] = requestData.id_token ? `Bearer ${requestData.id_token}` : '';
    
    const response = await axios.get(URLS.API_URL + URLS.GET_PROJECTS);

    const data = await response.data;

    return data;
    //return mockSearchData; // For testing, we return mock data

  } catch (error) {
    if (error instanceof AxiosError) {
      return rejectWithValue(error.response?.data || error.message);
    }
    return rejectWithValue('An unknown error occurred');
  }
});

// ResourcesState defines the shape of the resources slice of the Redux state.
// It includes an array of items, a status to track loading state, and an error message
type ProjectsState = {
  items: unknown; // Replace 'unknown' with your actual resource type
  status: 'idle' | 'loading' | 'succeeded' | 'failed';
  error: string | undefined | unknown | null;
  isloaded: boolean;
};

const initialState: ProjectsState = {
  items: [],
  status: 'idle',
  error: null,
  isloaded: false,
};

// createSlice generates actions and reducers for a slice of the Redux state.
export const projectsSlice = createSlice({
  name: 'projects',
  initialState,
  reducers: {
    setIsLoaded: (state, action) => {
      state.isloaded = action.payload.isloaded;
    }
  }, // No synchronous reducers needed for this slice
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk.
  extraReducers: (builder) => {
    builder
      .addCase(getProjects.pending, (state) => {
        state.status = 'loading';
        state.isloaded = false;
      })
      .addCase(getProjects.fulfilled, (state, action) => {
        state.status = 'succeeded';
        state.isloaded = true;
        state.items = action.payload; // Replace the list with search results
      })
      .addCase(getProjects.rejected, (state, action) => {
        state.status = 'failed';
        state.isloaded = false;
        state.error = action.payload; // Use payload from rejectWithValue
      });
  },
});

export const { setIsLoaded } = projectsSlice.actions;

export default projectsSlice.reducer;
